create table seminars (
	id bigint generated by default as identity,
	teachers varchar(255) not null,
	code varchar(255) not null,
	name varchar(255) not null,
	price decimal(19,2) not null,
	published_on date not null,
	scientific_manager varchar(255) not null,
	primary key (id)
);

create table students (
	id bigint generated by default as identity,
	city varchar(60) not null,
	email varchar(254) not null,
	name varchar(50) not null,
	phone_number varchar(15) not null,
	postal_code varchar(18) not null,
	surname varchar(50) not null,
	primary key (id)
);

create table vests (
	id bigint generated by default as identity,
	vest_date date not null,
	seminar_id bigint,
	student_id bigint,
	primary key (id)
);

CREATE TABLE USERS (
	username VARCHAR(255) PRIMARY KEY NOT NULL,
	password VARCHAR(255) NOT NULL,
	enabled TINYINT(1) NOT NULL,
	PRIMARY KEY (username)
);

CREATE TABLE AUTHORITIES (
	username VARCHAR(255) NOT NULL,
	authority VARCHAR(255) NOT NULL
);